"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# Read configuration values from environment variables/.env
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-ha4l*^^*)#u%nwf0to=u_p2k8y-+r#h+-!7iw2^*yz_$v=6+%g'
# Read sensitive settings from environment variables
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG is controlled from .env so that the development behaviour can change without editing the code
DEBUG = config("DEBUG", default=False, cast=bool)

# ALLOWED_HOSTS = []
# Hosts allowed during local Docker development
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]

# Allow frontend origins to call the Django backend during development.
# These are the browser origins that Django will allow for cross-origin JavaScript requests.
# http://localhost:5173 is the direct Vite development server.
# http://localhost and https://localhost are the Nginx reverse-proxy entrypoints.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost",
    "https://localhost",
]

# Allow cookies/session credentials to be included in cross-origin requests.
CORS_ALLOW_CREDENTIALS = True

# Trust these frontend origins for CSRF-protected requests such as POST login, signup, and logout.
# This does not disable CSRF protection; it only tells Django these origins are allowed to send CSRF-checked requests.
# https://localhost is needed after adding HTTPS through Nginx.
# CSRF (Cross-Site Request Forgery)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost",
    "https://localhost",
]

# Application definition

'''
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',s
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
'''
INSTALLED_APPS = [
    'users',    # In Django, Apps are features
    'rest_framework',   # add REST framework
    'corsheaders',  # add CORS
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Code that runs automatically during request/response process
# Chain of automatic processing steps around every request/response
MIDDLEWARE = [  
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',    # Add CORS middleware, run on top of everything else
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''

# Use PostgreSQL, the values come from .env through Docker Compose
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Use our custom user model instead of Django's default auth.User model.
AUTH_USER_MODEL = 'users.User'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
