server  {
    listen 80;  # listen for HTTP request on port 80.

    server_name localhost;

    # Docker's internal DNS resolver.
    # This lets Nginx resolve Docker Compose service names like "backend" and "frontend".
    # valid means: cache the result for 10 seconds to keep the cache short
    # Do not ask for IPv6 addresses. Only use IPv4 lookups.
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/  {   # If the browser request starts with /api/, send it to backend container.
        set $backend_upstream backend:8000;
        proxy_pass http://$backend_upstream;

        # Standard reverse-proxy headers.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /  {   # Everything else goes to the frontend container
        set $frontend_upstream frontend:5173;
        proxy_pass http://$frontend_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Nginx starts
#     ↓
# Nginx reads config
#     ↓
# It knows it should use Docker DNS: 127.0.0.11
#     ↓
# It does not crash immediately because backend is inside a variable
#     ↓
# Browser later requests /api/users/me/
#     ↓
# Nginx now resolves backend using Docker DNS
#     ↓
# Docker says backend = 172.xx.xx.xx
#     ↓
# Nginx forwards request to backend:8000